### ISSUE TITLE
xrv9k Unable to connect to qemu monitor

### ISSUE THREAD

**Issue by horseinthesky** [vrnetlab/vrnetlab#293]
Hello.

After successful `make make docker-image` I got and image
```
docker images            
REPOSITORY              TAG        IMAGE ID       CREATED          SIZE
vrnetlab/vr-xrv9k       7.6.1      123ad8d55c1e   21 minutes ago   1.9GB
```

Then I run
```
docker run -d --privileged --name my-xrv-router vrnetlab/vr-xrv9k:7.6.1
```

Logs:
```
2022-05-29 17:35:42,763: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 56)
2022-05-29 17:35:43,765: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 57)
2022-05-29 17:35:44,767: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 58)
2022-05-29 17:35:45,769: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 59)
2022-05-29 17:35:46,770: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 60)
Traceback (most recent call last):
  File "/launch.py", line 237, in <module>
    vr.start()
  File "/vrnetlab.py", line 353, in start
    vm.work()
  File "/vrnetlab.py", line 289, in work
    self.check_qemu()
  File "/vrnetlab.py", line 305, in check_qemu
    self.start()
  File "/vrnetlab.py", line 139, in start
    raise QemuBroken("Unable to connect to qemu monitor on port {}".format(4000 + self.num))
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 4000
```
and container stops.

**Comment by renesobral** [comment]
HI @horseinthesky,
Can you confirm that you have QEMU up and running? Also if yes, are you able to do a telnet connection on port 4000?

**Comment by horseinthesky** [comment]
> HI @horseinthesky, Can you confirm that you have QEMU up and running? Also if yes, are you able to do a telnet connection on port 4000?

Hey. Don't have the qemu lab anymore.
