### ISSUE TITLE
Fail to boot Cisco NXOS image

### ISSUE THREAD

**Issue by lemontree61089** [vrnetlab/vrnetlab#301]
Hello,

I am not able to boot Cisco Nexus image. Tried with image version 10.3.2.F and  9.3.10. 
Both give me the same error message:

```
docker run -it --rm --privileged vrnetlab/vr-nxos:9.3.9 ls -la /launch.py          
Traceback (most recent call last):
  File "/launch.py", line 13, in <module>
    import vrnetlab
  File "/vrnetlab.py", line 51
    logging.getLogger().info(f"Delaying VM boot of by {delay} seconds")
                                                                     ^
SyntaxError: invalid syntax
```

**Comment by lemontree61089** [comment]
Resolved this error by checkout to master branch
