### ISSUE TITLE
Can't build VMX image w/vmx-bundle-18.2R1.9

### ISSUE THREAD

**Issue by bvilajol** [vrnetlab/vrnetlab#314]
Hello,

Thanks a lot for the work you're doing. 

Build for named image ends with error once install is started:

```
Traceback (most recent call last):
  File "/launch.py", line 398, in <module>
    vr = VMX_installer(args.username, args.password, args.dual_re)
  File "/launch.py", line 325, in __init__
    super().__init__(username, password, dual_re)
  File "/launch.py", line 287, in __init__
    VMX_vfpc(self.version) ]
  File "/launch.py", line 208, in __init__
    self.version = version
```
version takes value 18.2R1.9 and version_info [18, 2, 'R', 1, 9].

Any test  - trace I could provide, just ask.

Thanks,

**Comment by bvilajol** [comment]
Hello,

After update error is different.

```
Traceback (most recent call last):
  File "/launch.py", line 381, in <module>
    vr = VMX_installer(args.username, args.password, args.dual_re)
  File "/launch.py", line 308, in __init__
    super().__init__(username, password, dual_re)
  File "/launch.py", line 281, in __init__
    self.vms = [ VMX_vcp(username, password, self.vcp_image, dual_re=True, re_instance=0),
AttributeError: 'VMX_installer' object has no attribute 'vcp_image'
```

```
git status

On branch master
Your branch is up to date with 'origin/master'.
```

No luck getting an older one yet... :-(

**Comment by mzagozen** [comment]
This one is my fault, sorry about that. I did some extra refactoring on the vmx launcher but when I was untangling the version handling code for #313 I missed a commit.
