### ISSUE TITLE
AOSCX not running - Qemu error 

### ISSUE THREAD

**Issue by Sadiqbk** [vrnetlab/vrnetlab#344]
AOSCX VM container image built using VRNETLAB on centos 9 stream KVM

2024-05-11 10:01:16,349: launch     DEBUG    Environment variables: environ({'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOSTNAME': 'aruba1', 'TERM': 'xterm', 'CLAB_LABEL_CLAB_TOPO_FILE': '/root/cLAB1/aruba.yml', 'CLAB_INTFS': '0', 'DOCKER_NET_V6_ADDR': '2001:172:20:20::/64', 'USERNAME': 'admin', 'CLAB_LABEL_CLAB_NODE_KIND': 'vr-aoscx', 'CONNECTION_MODE': 'tc', 'CLAB_LABEL_CONTAINERLAB': 'aruba', 'CLAB_LABEL_CLAB_NODE_GROUP': '', 'CLAB_LABEL_CLAB_NODE_LAB_DIR': '/root/cLAB1/clab-aruba/aruba1', 'PASSWORD': 'admin', 'CLAB_LABEL_CLAB_NODE_NAME': 'aruba1', 'CLAB_LABEL_CLAB_NODE_TYPE': '', 'DOCKER_NET_V4_ADDR': '172.20.20.0/24', 'DEBIAN_FRONTEND': 'noninteractive', 'HOME': '/root', 'LC_CTYPE': 'C.UTF-8'})
2024-05-11 10:01:16,349: vrnetlab   DEBUG    Creating overlay disk image
2024-05-11 10:01:16,365: vrnetlab   DEBUG    Starting vrnetlab AOSCX
2024-05-11 10:01:16,365: vrnetlab   DEBUG    VMs: [<__main__.AOSCX_vm object at 0x7f6b95aaed60>]
2024-05-11 10:01:16,370: vrnetlab   DEBUG    VM not started; starting!
2024-05-11 10:01:16,371: vrnetlab   INFO     Starting AOSCX_vm
2024-05-11 10:01:16,371: vrnetlab   DEBUG    number of provisioned data plane interfaces is 0
2024-05-11 10:01:16,371: vrnetlab   DEBUG    qemu cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -m 4096 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=/arubaoscx-disk-image-genericx86-p4-20240129204649-overlay.vmdk -cpu host,level=9 -smp 2 -device pci-bridge,chassis_nr=1,id=pci.1 -device virtio-net-pci,netdev=p00,mac=0C:00:d0:41:a1:00 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443
2024-05-11 10:01:16,600: vrnetlab   INFO     STDOUT: 
2024-05-11 10:01:16,600: vrnetlab   INFO     STDERR: qemu-system-x86_64: error: failed to set MSR 0x345 to 0x2000
qemu-system-x86_64: ../../target/i386/kvm.c:2701: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.

2024-05-11 10:01:16,602: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 1)
2024-05-11 10:01:17,604: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 2)
2024-05-11 10:01:18,605: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 3)
2024-05-11 10:02:15,690: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 60)
Traceback (most recent call last):
  File "/launch.py", line 189, in <module>
    vr.start()
  File "/vrnetlab.py", line 762, in start
    vm.work()
  File "/vrnetlab.py", line 680, in work
    self.check_qemu()
  File "/vrnetlab.py", line 694, in check_qemu
    self.start()
  File "/vrnetlab.py", line 216, in start
    raise QemuBroken(
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 4000

**Comment by mzagozen** [comment]
Hi @Sadiqbk, this repository does not support the AOS-CX platform. If you're still experiencing the problems described, please open an issue in https://github.com/hellt/vrnetlab
